######################################################################
# Automatically generated by qmake (3.0) Sat Nov 11 20:19:24 2017
######################################################################

TEMPLATE = app
TARGET = run_ssh_agent_and_cmder
INCLUDEPATH += .

# Input
SOURCES += main.cpp
